//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JerslevKroMVC.Resources.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om Jerslev Kro.
        /// </summary>
        public static string h2_1 {
            get {
                return ResourceManager.GetString("h2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historen om Jerslev Kro.
        /// </summary>
        public static string h3_1 {
            get {
                return ResourceManager.GetString("h3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kroen er grundlagt i 1842 i Jerslev tæt på Brønderslev.
        ///.
        /// </summary>
        public static string p_1 {
            get {
                return ResourceManager.GetString("p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der lejes også værelser ud på kroen. De har været meget benyttet af blandt andet rejsemontører med mere..
        /// </summary>
        public static string p_10 {
            get {
                return ResourceManager.GetString("p_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er første gang (Mark&apos;s mor og far) kan kalde sig kroejer..
        /// </summary>
        public static string p_11 {
            get {
                return ResourceManager.GetString("p_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to – Så nu skal de have nye projekter i gang, siger de..
        /// </summary>
        public static string p_12 {
            get {
                return ResourceManager.GetString("p_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerslev Kro er en hyggelig gammel kro, i hyggelige omgivelser, der har været kgl. privilegeret..
        /// </summary>
        public static string p_2 {
            get {
                return ResourceManager.GetString("p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stedet emmer af historie og landlig idyl..
        /// </summary>
        public static string p_3 {
            get {
                return ResourceManager.GetString("p_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man føler sig dejlig afslappet,.
        /// </summary>
        public static string p_4 {
            get {
                return ResourceManager.GetString("p_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da der er en rolig og hyggelig atmosfære. Hyggelige værelser og naturlige omgivelser, giver fantastiske rammer om et hvert selskab, udflugt eller en hyggelig middag i godt selskab..
        /// </summary>
        public static string p_5 {
            get {
                return ResourceManager.GetString("p_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er igen liv i den kongeligt privilegerede Jerslev Kro. (Mark&apos;s mor og far) har åbnet kroen..
        /// </summary>
        public static string p_6 {
            get {
                return ResourceManager.GetString("p_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åbningen blev markeret med en reception for kunder, forretningsforbindelser og andre med tilknytning til kroen..
        /// </summary>
        public static string p_7 {
            get {
                return ResourceManager.GetString("p_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der blev udtrykt stor glæde over, at kroen igen er i drift. Kroen har været lukket siden i sommer..
        /// </summary>
        public static string p_8 {
            get {
                return ResourceManager.GetString("p_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Mark&apos;s mor og far) har krostuen åbent hver dag, mens de endnu ikke har besluttet sig for omfanget af brug af salen. Åbningstiden er længere i weekenden end på hverdage..
        /// </summary>
        public static string p_9 {
            get {
                return ResourceManager.GetString("p_9", resourceCulture);
            }
        }
    }
}
