//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JerslevKroMVC.Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mors dag d. 9. Maj.
        /// </summary>
        public static string h1_1 {
            get {
                return ResourceManager.GetString("h1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kro med traditionel, dansk mad &amp; hygge.
        /// </summary>
        public static string h2_1 {
            get {
                return ResourceManager.GetString("h2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kroophold i idylliske omgivelser.
        /// </summary>
        public static string h3_1 {
            get {
                return ResourceManager.GetString("h3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt os for bestilling.
        /// </summary>
        public static string h3_2 {
            get {
                return ResourceManager.GetString("h3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerslev kro vil selvfølgelig også fejre vores mødre, derfor tilbyder vi flæskesteg med kartofler, skysauce og chips til ½ pris (65,-)
        ///                til mødrene der bliver inviteret ud, d. 9. Maj fra kl. 17.00 til 20.00, her på kroen..
        /// </summary>
        public static string p_1 {
            get {
                return ResourceManager.GetString("p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fra Torsdag d. 6. Maj er der ikke længere krav om
        ///            bordbestilling, dog stadig krav om mundbind
        ///            og gyldig Coronapas..
        /// </summary>
        public static string p_2 {
            get {
                return ResourceManager.GetString("p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hos Jerslev Kro har vi fokus på traditionel, dansk hygge. Søger du et kroophold i Jerslev eller Brønderslev, har vi de perfekte rammer, egen restaurant,
        ///                højt serviceniveau og generelt en stemningsfyldt kro. Skal du holde selskab, overnatte eller måske holde en lille ferie, er du altid velkommen hos os..
        /// </summary>
        public static string p_3 {
            get {
                return ResourceManager.GetString("p_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Som kro kan vi tilbyde masser af forskellige muligheder. Her er både den traditionelle krostue og restaurant, gode overnatningsmuligheder, selskabslokaler og mødefaciliteter.
        ///                Skal du eksempelvis holde julefrokost, er det muligt at gøre hos os, hvor vi sørger for det hele. Og du kan kombinere det med et kroophold, hvor gæsterne kan overnatte..
        /// </summary>
        public static string p_4 {
            get {
                return ResourceManager.GetString("p_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vores kro ligger rolige omgivelser i smukke Nordjylland, hvorfor et kroophold hos os er ren balsam for både krop og sind..
        /// </summary>
        public static string p_5 {
            get {
                return ResourceManager.GetString("p_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi gør en dyd ud af at skabe den velkendte danske hygge, da vi sætter stor pris på alle vore gæster og gerne vil give dem et mindeværdigt ophold..
        /// </summary>
        public static string p_6 {
            get {
                return ResourceManager.GetString("p_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er også muligt at bestille mad ud af huset, hvis du skal holde selskab eller nytår et andet sted. Vi laver gerne maden til festen, så du kan koncentrere dig om at være en god vært..
        /// </summary>
        public static string p_7 {
            get {
                return ResourceManager.GetString("p_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi byder dig velkommen her på kroen, hvor der altid er et venligt og imødekommende personale, der har fokus på dine ønsker og behov..
        /// </summary>
        public static string p_8 {
            get {
                return ResourceManager.GetString("p_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker du at bestille et kroophold, nytårsmenu, overnatning eller middag i vores kro,
        ///                kan du altid ringe at bestille på telefon 98 83 11 88 eller skrive til os på info@Jerslev-kro.dk.
        /// </summary>
        public static string p_9 {
            get {
                return ResourceManager.GetString("p_9", resourceCulture);
            }
        }
    }
}
