//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JerslevKroMVC.Resources.MyTexts", typeof(MyTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORSIDE.
        /// </summary>
        public static string FORSIDE {
            get {
                return ResourceManager.GetString("FORSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKKE LAVET.
        /// </summary>
        public static string IKKE_LAVET {
            get {
                return ResourceManager.GetString("IKKE_LAVET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OM JERSLEV KRO.
        /// </summary>
        public static string OM_JERSLEV_KRO {
            get {
                return ResourceManager.GetString("OM_JERSLEV_KRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OM OS.
        /// </summary>
        public static string OM_OS {
            get {
                return ResourceManager.GetString("OM_OS", resourceCulture);
            }
        }
    }
}
